### ISSUE TITLE
New municipality REST - to replace old regions and deceased-regions.csv (merged)

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data-api#35]
Pri implementaciji umrlih po občinah smo ugotovili, da bi bilo veliko bolje, če bi lahko podatke o posameznih občinah združili v en model in REST interface. Ideja je, da bi ta interface nadomestil obstoječi regions/decease-regions tako, da bi sa posamezno občino imeli več polj:
- `TestsPositiveToDate` (iz regions.csv)
- `DeceasedToDate` (iz deceased_regions.csv)

V bodoče bi lahko dodali še dodatne izračunane podatke v model (recimo recovered ali active).
Tako bi iz same 2D predstavitve v GDocs/CSV prešli na veliko bolj uporabno predstavitev podatkov o sami občini.

Glede implementacije pa vidim več možnosti:
1. REST server to združi sam (je načeloma dokaj trivialno, ko imaš oba mapa naložena iz CSV)
2. Naredimo nov `municipality.csv`, ki združuje Kraji in Umrli:Kraji model (export skripta združi 2 tabeli - @overlordtm)
3. V GDocs naredimo novo kumulativno tabelo Občine tabelo 
(ala Pacienti - več stolpcev za za vsako občino) - si pa malo težje predstavljam kako bo to izgledalo, ker bo ogromno stolpcev in bo težko zagotavljati header ključe za export 

Mogoče dobro, da se danes @MihaMarkic in @overlordtm slišimo in vidimo, kaj je najhitreje narejeno. Meni je opcija 2 najboljša, ker bi še vedno imeli enoten CSV in REST in tudi pri CSV je lažje če imaš vse v enem modelu.

**Comment by MihaMarkic** [comment]
Kot se odločite. Verjetno je za vas res najbolje 2.

**Comment by lukarenko** [comment]
@overlordtm mislim da bi bil tak merge tudi relativno enostaven za skripto:
- za Kraji dodaš ključu .confirmed.todate
- za Kraji: Umrli pa ključu dodaš .deceased.todate
Potem pa samo dan po dan exportaš.

**Comment by overlordtm** [comment]
Tole bo kul? https://github.com/sledilnik/data/blob/merged-data/csv/municipality.csv

**Comment by overlordtm** [comment]
Zmergano na master https://github.com/sledilnik/data/blob/merged-data/csv/municipality.csv

**Comment by lukarenko** [comment]
@overlordtm jaz bi samo `tests.positive.todate` preimenoval v `cases.confirmed.todate` - tests.positive sedaj uporabljamo samo za poročila laboratorijev in se ne ujema 100% z epidemiološkim poročilom. Podatki po občinah pa iz epidemiološkega poročila.

@MihaMarkic a boš lahko dodal nov api/municipalities, ki bo vseboval obe podatka za vsak dan/regijo/občino?
`regions` in `deceased-regions` pa bi lahko označili kot deprecated in lahko počasi ukinili - za preveriti če ga še kdo uporablja - to bo zdaj zaradi prehoda na api.sledilnik.org relativno enostavno videti.

**Comment by MihaMarkic** [comment]
Renamed first column in csv to 'date'

**Comment by MihaMarkic** [comment]
@lukarenko A lahko poimenuješ prvi stolpec 'date'? Da bo po istem kopitu kot ostali. Sem preimenoval, sam v merged-data veji, verjetno je potrebno kaj več.
