### ISSUE TITLE
Add .timestamp into each REST API

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data-api#36]
We have .timestamp files with last update of each CSV files. We would need to add this timestamp to each REST API.

**Comment by overlordtm** [comment]
I see two options: 

1) Separate endpoint for timestamps
2) return timestamp in header (i would prefer this, single call)

Also, there is edge case when you can manage to fetch new timestamp, but no new data (due to GH down)

**Comment by MihaMarkic** [comment]
Headers definitely. You can't fetch just timestamps. You would fetch csv and not timestamps, but not the other way round.
So, what happens then?
