### ISSUE TITLE
Patients: expose all deceased fields via REST

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data-api#38]
Currently we export the following:
```
"deceased": {
  "toDate": 96,
  "hospital": 1,
  "home": 1,
  "icu": 1,
  "today": 2
}
```

Only total number is exposed as today + toDate, while others expose only today number (it seems).

I would suggest the following format:
```
"deceased": {
  "toDate": 96,
  "today": 2
  "home":  {
    "toDate": 24,
    "today": 1
   }
  "hospital": {
    "toDate": 96,
    "today": 2
    "icu":  {
      "toDate": 24,
      "today": 1
     }
   }
}
```

For individual hospitals, we would get:
```
"deceased": {
  "toDate": 96,
  "today": 2
  "icu":  {
    "toDate": 24,
    "today": 1
   }
}
```

Since home/hospital/icu was not use, I think such change is safe to do...

**Comment by lukarenko** [comment]
2nd option (to not complicate with nesting) is just to add additional deceased fields:

```
"deceased": {
  "toDate": 96,
  "today": 2
}
"deceased-home":  {
    "toDate": 24,
    "today": 1
}
"deceased-hospital": {
  "toDate": 96,
  "today": 2
}
"deceased-hospital-icu":  {
   "toDate": 24,
    "today": 1
}
```
Maybe this one is better as it is then similar for total and per-hospital

**Comment by lukarenko** [comment]
And we are currently using the following field: total.deceased.hospital
So we cannot just break it. Therefore 2nd option seems better.

**Comment by MihaMarkic** [comment]
Went with the first option since it's cleaner and in more in sync with the rest. You have a staging version on rthand.com, so the frontend can be updated.
