### ISSUE TITLE
Add timestamp to header

### ISSUE THREAD

**Issue by miaerbus** [sledilnik/data-api#39]

**Comment by MihaMarkic** [comment]
@lukarenko A za timestamp se uporabi vrednost iz .timestamp naslova? Ker v glavi .CSVja ne dobim nič uporabnega. In kaj je sploh tista vrednost? Milisekunde od 1970 naprej?

**Comment by lukarenko** [comment]
Ja, timestamp je v svojem fajlu in v UNIX time

**Comment by MihaMarkic** [comment]
Očitno sem se motil (gledal mojo staro produkcijsko verzijo). Timestamp je že na voljo, implementirano v #36

**Comment by MihaMarkic** [comment]
Timestamp header isn't available to client because CORS is not allowing it.
