### ISSUE TITLE
Stats-weekly.csv - new API

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data-api#44]
A bi lahko stats-weekly.csv spravii v api? Lahko še kaj predelamo csv, če je potreba...https://github.com/sledilnik/data/blob/master/csv/stats-weekly.csv

**Comment by MihaMarkic** [comment]
@lukarenko .src. stands for source?

**Comment by lukarenko** [comment]
Ja, source (izvor). To je za importirane iz posameznih držav. Lahko daš importedFrom.
