### ISSUE TITLE
Extend OurWorldInData API with columns query parameter

### ISSUE THREAD

**Issue by breki** [sledilnik/data-api#51]
In order to show some new graphs, we would need an extension of the API: a additional (mandatory) `columns` query parameter that lists (comma-separated) the actual OWID columns to return in the dataset, for example: `columns=hosp_patients_per_million,icu_patients_per_million`.

This also means the backend should store all of OWID data (if it doesn't do that already). 

@MihaMarkic does this affect the caching solution in any way?

cc: @lukarenko, @joahim

**Comment by MihaMarkic** [comment]
@breki  we already store all data (I think) and it wouldn't affect caching. It might affect the way we filter it though

**Comment by MihaMarkic** [comment]
Perhaps we could simply return all columns all the time?

**Comment by breki** [comment]
That's too much data, that's around 50 columns. Then we will again have problems with slow rendering on the browser and high CPU usage.
What is the problem with filtering?

**Comment by MihaMarkic** [comment]
@breki Duh, refactoring was quite some work. Give it a try - owid branch it is.

**Comment by breki** [comment]
@MihaMarkic thanks, will check ASAP

**Comment by MihaMarkic** [comment]
Hey @breki, can we close this issue?

**Comment by breki** [comment]
Sure, thanks!
