### ISSUE TITLE
New API: lab-tests.csv

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data-api#55]
We have new data-set: LAB tests by laboratory:
https://github.com/sledilnik/data/blob/master/csv/lab-tests.csv

We would need similar setup as with patients.csv, where we have per-hospital data, here we have per-lab data + split of regular and national survey from apr tests

**Comment by lukarenko** [comment]
Related CSV is documented here:
https://github.com/sledilnik/data/pull/37

**Comment by MihaMarkic** [comment]
Closed by e70edeb
