### ISSUE TITLE
Add api/schools

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data-api#74]
We need new API for schools-cases.csv:
https://github.com/sledilnik/data/blob/master/csv/schools-cases.csv

Type:
- `kindergarten`
- `elementary`
- `elementary_special`
- `music`
- `highschool`
- `dormitory`
- `institutions`

Sample fields:
- `kindergarten.employees.confirmed`
- `kindergarten.employees.active`
- `kindergarten.attendees.confirmed`
- `kindergarten.attendees.active`
- `kindergarten.attendees.to_quarantine`
- `kindergarten.attendees.quaranteened`
- `kindergarten.units.to_quarantine`
- `kindergarten.units.quaranteened`
- `kindergarten.units.remote`

**Comment by MihaMarkic** [comment]
Updated in 1.10.0
